### ISSUE TITLE
Uses xorg

### ISSUE THREAD

**Issue by AlexBMJ** [Maroka-chan/ansible-desktop#1]
You misspelled wayland

[main.yml](/Maroka-chan/ansible-desktop/blob/master/roles/common/defaults/main.yml)
`display_server: xorg` <- 🤔

Possible fix: replace xorg with sway 😘

**Comment by Maroka-chan** [comment]
damn my bad 😖

I kwinda need the compwatibiwity to bwe an epwic gamer uwu~
You awe fwee to add a twask for wayland if youwe gwot the twime~
That would bwe twuly pwoggers 😳 uwu
